{
 "title": "Fraud Risk Intelligence Platform",
 "tags": [
  "fraud",
  "fastapi",
  "ml"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total API Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fraud_api_http_requests_total)",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fraud_api_http_requests_total[5m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fraud_api_http_requests_total{status_code=~\"4..|5..\"})",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(fraud_api_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Predictions By Risk Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (risk_level) (fraud_predictions_total)",
     "legendFormat": "{{risk_level}}"
    }
   ]
  },
  {
   "title": "Final Decisions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (final_decision) (fraud_predictions_total)",
     "legendFormat": "{{final_decision}}"
    }
   ]
  }
 ]
}