apiVersion: v1
kind: Secret
metadata:
  name: fraud-postgres-secret
  namespace: fraud-risk
type: Opaque
stringData:
  DATABASE_URL: "postgresql://CHANGE_ME:CHANGE_ME@managed-postgres.example.com:5432/fraud_db"
  FRAUD_API_KEY: "CHANGE_ME"
  JWT_SECRET_KEY: "CHANGE_ME"
